### ISSUE TITLE
NoSuchMethodError com.squareup.javapoet.TypeSpec.classBuilde on 0.3.1

### ISSUE THREAD

**Issue by Maragues** [rharter/auto-value-gson#43]
After upgrading to 0.3.1, building the project throws this error

*Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
          > java.lang.NoSuchMethodError: com.squareup.javapoet.TypeSpec.classBuilder(Lcom/squareup/javapoet/ClassName;)Lcom/squareup/javapoet/TypeSpec$Builder;*

Reverting to 0.2.5 fixes the issue. These are the *build.gradle* lines concerning auto-value

*apt 'com.ryanharter.auto.value:auto-value-gson:0.3.1'
    apt 'com.ryanharter.auto.value:auto-value-parcel:0.2.1'
    apt 'com.google.auto.value:auto-value:1.2'
    provided 'com.google.auto.value:auto-value:1.2'
    provided 'javax.annotation:jsr250-api:1.0'*

There are many more dependencies (retrofit2, picasso, rx, etc.). Let me know if you need the full list.

Thanks!

**Comment by gabrielittner** [comment]
Which other `apt` dependencies do you have? Do you use Dagger 2?

**Comment by Maragues** [comment]
*apt 'com.google.dagger:dagger-compiler:2.2'
apt 'com.jakewharton:butterknife-compiler:8.0.1'*

**Comment by gabrielittner** [comment]
Dagger 2.2 bundles an older version of JavaPoet. There are two possible solutions. You can explicitly add `apt 'com.squareup:javapoet:1.7.0'` before `apt 'com.google.dagger:dagger-compiler:2.2'` to fix this.

**Comment by Maragues** [comment]
Thanks, that fixed the issue

**Comment by TWiStErRob** [comment]
https://github.com/rharter/auto-value-gson/issues/43#issuecomment-219994018 what's he other one?
